Makefile.PL

In 6.99_something, ExtUtils::MakeMaker began quoting all the make variables, so
regexps need to be updated to account for that.

Fix build with ExtUtils::MakeMaker 7.00+ and Perl 5.21.6+.

---

Makefile.PL

I've tested this in a limited way on Ubuntu, Mac, and Windows. This essentially incorporates kmx's hack, using `dirname(__FILE__)` to obtain the current module directory. I believe it addresses Ingo's issues from #29.

Make Prima::Config relocatable

---

Makefile.PL

Reverts dk/Prima#30
Well I knew I've neen too hasty ... here's how it fails on linux:
dk@udayin src/IPA> perl -MPrima::Config -le 'print $Prima::Config::Config{gencls}'
/home/dk/perl5/perlbrew/perls/perl-5.14.2/lib/site_perl/5.14.2/i686-linux/Prima/../../bin/gencls
dk@udayin src/IPA> which gencls
/home/dk/perl5/perlbrew/perls/perl-5.14.2/bin/gencls

Revert "Make Prima::Config relocatable"

---

Prima/PS/Drawable.pm

An extra parenthesis (possibly left over from a copy-and-paste) led to compiler errors. This patch removes it.

Remove errant parenthesis

---

t/Image/Bar.t

This test was failing under headless X11 systems. Removing the
use of Prima::Application seems to fix the problem.

Fix t/Image/Bar.t under headless X11

---

Makefile.PL

Current `Makefile.PL` relies on the EUMM-generated `Makefile` having no spaces before `:` in rules. This patch removes that assumption, which is incorrect from EUMM 7.11_02. This addresses:
* this cpantesters failure: http://www.cpantesters.org/cpan/report/ce4cbb5e-917f-11e5-8342-5a9f251cf1b3
* this RT report: https://rt.cpan.org/Ticket/Display.html?id=109962
* this EUMM issue (which tracks blockers for EUMM 7.12): https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/issues/252

EUMM compatibility update

---

Prima.pm
examples/calendar.pl
examples/dwm_blur.pl
examples/generic.pl

Hi,
I received your dist in this month's [CPAN PR Challenge](http://cpan-prc.org/).  When looking through the docs and examples, I noticed a few places where usage of indirect object syntax was still in use.
This minimal set of changes uses the ```Foo->new()``` syntax instead.
Thanks,
Chase

Indirect object syntax

---

Prima/FrameSet.pm

With this finally "separatorWidth" property makes sense. Without this, you can not change the width of the separataor, if you use the option "flexible => 0"!
I really think, it is just a misspelling..
Best wishes, Max

Correcting a literal error I think

---

Prima/Sliders.pm
Prima/Spinner.pm

Hello Dmitry,
I would like to make the drops style as the default style. I forwent doing this first because my version of drops looked not very good. But after your enhancement the drop style is fantastic.
I would also like to propose to change the style name of the "yinyang" style to "spiral" because I think "yinyang" was not very meaningful and describes the style not very good.
Lastly I added pod Docu for the spiral style and improved minor misspelling..
Best wishes,
Max

Make "drops" style as default in Prima::Spinner and add "indeterminate" mode to Prima::Gauge

---

Prima/Sliders.pm

Hello Dmitry,
Enclosed the changes you wished:
-> $self->{direction} is not user-settable any more
-> $self->{timer} is only created in indeterminate mode...

Prima::Gauge: direction not settable & timer not in determinate Gauge

---

unix/window.c

Hi Dmitry,
In my bin/fullscreen of [twitham1/LPDB](https://github.com/twitham1/LPDB) I noticed the geometry of the frame was not reported correctly under X11.  This seems to fix that.

Fix frameOrigin and frameSize on unix/x11

---

img/rotate.c

Decrementing io when it is at the start of the object sends it out of bounds, thus invoking undefined behaviour.  Always increment the pointer instead.
Resolves: #78

Avoid invalidating pointer

---

img/codec_bmp.c

GCC 13 warns:
In function 'destroy_ahead',
inlined from 'load' at img/codec_bmp.c:875:10:
img/codec_bmp.c:214:26: warning: pointer 'ahead_1042' used after 'free' [-Wuse-after-free]
214 |         if (error & ahead-> fi-> wasTruncated) error = false;
|                     ~~~~~^~~~~
img/codec_bmp.c:213:9: note: call to 'free' here
213 |         free(ahead);
|         ^~~~~~~~~~~
This patch fixes it by swapping the two lines.

Fix a use-after free in destroy_ahead()

---

MANIFEST
Prima.pm
utils/prima-pod2pdf.pl

pod2pdf name is already used by JONALLEN/pod2pdf-0.42.tar.gz CPAN distribution. This patch adds a prima- prefix as it is already used in utils/prima-tmlink.pl.
CPAN RT#151521

Rename pod2pdf to perl-pod2pdf

---

Makefile.PL

The Makefile.PL checks produce warnigs with -Wall in CFLAGS:
~~~~
Checking for presence of type int8_t...
gcc -D_REENTRANT -D_GNU_SOURCE -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fwrapv -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -fopenmp -Iinclude -Iinclude/generic -o /tmp/pmts0000  /tmp/pmts0000.c -lpthread -shared -Wl,-z,relro …

Silent warnings about unused variable in type checks

---

Makefile.PL

Makefile.PL checks for available functions by assigning their address to a variable. Value of the variable is then never used and GCC warns like this:
/tmp/pmts0000.c: In function ‘main’:
/tmp/pmts0000.c:7:12: warning: unused variable ‘ixi’ [-Wunused-variable]
7 |     void * ixi = strcasecmp;
|            ^~~
and like this:
/usr/lib64/perl5/CORE/XSUB.h:166:20: warning: unused variable ‘items’ [-Wunused-variable]
166 | #define dITEMS I32 items = (I32)(SP - MARK)
|                    ^~~~~
/usr/lib64/perl5/CORE/XSUB.h:169:23: note: in expansion of macro ‘dITEMS’
169 |         dSP; dAXMARK; dITEMS
|                       ^~~~~~
/tmp/pmts0000.c:8:4: note: in expansion of macro ‘dXSARGS’
8 |    dXSARGS;
|    ^~~~~~~
This patch silents the warnings.

Silent warnings about unsused variables in Makefile.PL probes

---

Makefile.PL

Also has 3-arg open, and clean up more files on `make clean`.

Fix to work in place-with-space

---

Prima/Grids.pm

The examples are now separated from flowing text by an empty line, and indented so that POD readers don't flow them into each other.
A few local links are written L</...> instead of L<...>.
Tested in podview as well :)

Prima/Grids.pm: POD formatting suggestions

---

class/Widget/grid.c

The `sticky` option for `gridConfigure` works opposite to what I expect for `sticky => 'n'` and `sticky => 's'`.
My example code (again derived from your grid example with small changes):
```perl
use 5.020;
use strict;
use warnings;
use Prima qw(Application Label);
my $w = Prima::MainWindow->new(
backColor => cl::Gray,
);
$w->insert(
[Label => name => 'north', backColor => cl::Red],
[Widget => name => 'g', backColor => cl::Green],
[Label => name => 'south', backColor => cl::Blue],
[Widget => name => 'y', backColor => cl::Yellow],
);
$w->gridConfigure(north => row => 0, column => 0, sticky => 'n');
$w->gridConfigure(g => row => 0, column => 1,);
$w->gridConfigure(south => row => 1, column => 0, sticky => 's');
$w->gridConfigure(y => row => 1, column => 1);
run Prima;
```
This puts the …

grid: fix sticky=>'n' and sticky=>'s' positioning

---

examples/gt_grid.pl

This is an example of the grid geometry manager, demonstrating `rowspan` / `colspan` and cell padding.
I noticed two things:
- There is no `padx` / `pady` padding to the right of the rightmost column nor above the topmost row. A [comment](https://github.com/dk/Prima/blob/a826a80685a4aa0595777fd48cf2d46fa85c275d/class/Widget/grid.c#L189) in grid.c suggests that half of the padding should appear on either side, but as far as I understand the C code, padLeft and padX have the [same value,](https://github.com/dk/Prima/blob/a826a80685a4aa0595777fd48cf2d46fa85c275d/class/Widget/grid.c#L1979) leaving nothing left for the other side.
- The documentation of the `ipadx` option says "The amount must be a valid screen distance, such as 2 or '.5c'." but it does not process units like `.5c` .  Since …

Add examples/gt_grid.pl as a demo of the grid geometry manager

---

unix/gtk.c

Signals sent to the application propagate to the whole process group.  If a Prima application handles / ignores a signal, the same signal can kill the child, which (correctly) discards any signal handlers set by the application.
The patch puts the child in its own process group so that it does no longer receive signals sent to the parent process.
This came up in a discussion on PDL: https://github.com/PDLPorters/pdl/pull/492

unix/gtk.c: Make Prima's child process robust against signals
